### ISSUE TITLE
Migrate to GitHub Actions

### ISSUE THREAD

**Issue by zepatrik** [ory/changelog#2]
I think it is a good idea to make this a GH action, what do you think @aeneasr ?

**Comment by aeneasr** [comment]
The current CirlceCI pipeline depends on this as we use it to generate the notification emails, I'm not sure how well that would work in combination with GH Actions

**Comment by zepatrik** [comment]
I know, would rewrite it to run on GH actions as that would be a better fit.

**Comment by aeneasr** [comment]
I think you misunderstood. This repository is the template directory for generating the changelog using the changelog-generator cli command.

CircleCI fetches this repo with nom (I think) and then uses `changelog-generator` with a flag pointing to this repository. Doing this is required as part of the CircleCI build chain because we need to use the email template (defined in this repo) to generate the mailchimp template.

What could be done is write a small GH action that generates the `CHANGELOG.md` as a GitHub action but I could imagine this becoming difficult because we use a lot of git push to master when releasing software, and the task list is written in such a way that these don't run in parallel as to avoid racy pushes.

**Comment by zepatrik** [comment]
Ok right, I thought it is nicer to generate the changelog in GH actions because we would have way more triggers available but makes sense to have this non racy.
